service: zircon
provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-1
  memorySize: 128
  timeout: 1

functions:
  apiLookup:
    handler: api.lookup
    events:
      - http:
          path: /{proxy+}
          method: get
          cors: true
  popLookup:
    handler: pop.lookup
    iamRoleStatements:
    - Effect: Allow
      Action:
        - "*"
      Resource: "*"
